import React, { useState } from 'react'
import TopologySelector from './TopologySelector'
import ConvergenceComparator from './ConvergenceComparator'
import ExponentialLawExplorer from './ExponentialLawExplorer'
import styles from '../styles/ModuleStyles.module.css'

type TabType = 'topology' | 'convergence' | 'exponential'

const FunctionSpacesModule: React.FC = () => {
  const [activeTab, setActiveTab] = useState<TabType>('topology')

  const renderContent = () => {
    switch (activeTab) {
      case 'topology':
        return (
          <div>
            <div className={styles.explanation}>
              <h3>Understanding Function Space Topologies</h3>
              <p>
                Function spaces are sets of functions equipped with a topology. Different topologies on the same 
                function space can have dramatically different properties.
              </p>
              <ul>
                <li><strong>Pointwise Convergence:</strong> A sequence of functions converges if it converges at each point individually</li>
                <li><strong>Uniform Convergence:</strong> Functions converge if they converge at the same rate everywhere</li>
                <li><strong>Compact-Open Topology:</strong> The standard topology for continuous function spaces, generated by sets of functions mapping compact sets into open sets</li>
              </ul>
              <p>
                Use the selector below to explore how different topologies affect convergence and continuity properties.
              </p>
            </div>
            <TopologySelector />
          </div>
        )
      
      case 'convergence':
        return (
          <div>
            <div className={styles.explanation}>
              <h3>Comparing Convergence Types</h3>
              <p>
                In function spaces, the choice of topology determines what it means for a sequence of functions to converge.
                This has profound implications for analysis and functional analysis.
              </p>
              <ul>
                <li><strong>Pointwise vs Uniform:</strong> Uniform convergence preserves continuity, while pointwise convergence may not</li>
                <li><strong>Convergence and Limits:</strong> The limit of continuous functions is continuous under uniform convergence</li>
                <li><strong>Practical Impact:</strong> Different convergence types are useful in different contexts (e.g., Fourier series, approximation theory)</li>
              </ul>
              <p>
                The comparator below visualizes how the same sequence behaves under different convergence criteria.
              </p>
            </div>
            <ConvergenceComparator />
          </div>
        )
      
      case 'exponential':
        return (
          <div>
            <div className={styles.explanation}>
              <h3>The Exponential Law in Topology</h3>
              <p>
                The exponential law is a fundamental relationship in topology that connects function spaces with product spaces.
                When it holds, it states that:
              </p>
              <div className={styles.formula}>
                C(X × Y, Z) ≅ C(X, C(Y, Z))
              </div>
              <p>
                <strong>Important:</strong> This law requires Y to be locally compact Hausdorff for the homeomorphism to hold
                when C(Y, Z) has the compact-open topology. Without these conditions, the correspondence may fail!
              </p>
              <ul>
                <li><strong>Local Compactness:</strong> Every point has a compact neighborhood - this ensures the evaluation map is continuous</li>
                <li><strong>Hausdorff Property:</strong> Distinct points have disjoint neighborhoods - this ensures uniqueness of limits</li>
                <li><strong>Currying:</strong> Transform a function of two arguments into a function returning a function</li>
                <li><strong>Applications:</strong> This law is crucial in homotopy theory, where we often work with locally compact spaces</li>
              </ul>
              <p>
                The explorer below demonstrates this correspondence with concrete examples.
              </p>
            </div>
            <ExponentialLawExplorer />
          </div>
        )
      default:
        return null
    }
  }

  return (
    <div className={styles.module}>
      <div className={styles.tabs}>
        <button
          className={`${styles.tab} ${activeTab === 'topology' ? styles.active : ''}`}
          onClick={() => setActiveTab('topology')}
        >
          Topology Selector
        </button>
        <button
          className={`${styles.tab} ${activeTab === 'convergence' ? styles.active : ''}`}
          onClick={() => setActiveTab('convergence')}
        >
          Convergence Comparator
        </button>
        <button
          className={`${styles.tab} ${activeTab === 'exponential' ? styles.active : ''}`}
          onClick={() => setActiveTab('exponential')}
        >
          Exponential Law
        </button>
      </div>
      
      <div className={styles.content}>
        {renderContent()}
      </div>
    </div>
  )
}

export default FunctionSpacesModule